name: 'Swift Test'
description: 'Run swift test on a swift package.'
inputs:
  version:
    description: 'The swift version to use.'
    required: true
    default: 'latest'
  command:
    description: 'The swift command to run'
    required: true
    default: '--version'
runs:
  using: 'docker'
  image: 'swift:${{ inputs.verison }}'
  steps:
    - run: swift --version
